//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_Polzovateli
    {
        public int polzovateli_id { get; set; }
        public string login_polzovatelya { get; set; }
        public string parol { get; set; }
        public string imya { get; set; }
        public string familiya { get; set; }
        public string otchestvo { get; set; }
        public Nullable<int> id_roli { get; set; }
        public Nullable<bool> zablokirovan { get; set; }
    
        public virtual Demo_Roli Demo_Roli { get; set; }
    }
}
