//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user182_dbEntities : DbContext
    {
        private static user182_dbEntities _context;
        public user182_dbEntities()
            : base("name=user182_dbEntities")
        {
        }
        public static user182_dbEntities GetContext()
        {
            if (_context == null)
                _context = new user182_dbEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Demo_Polzovateli> Demo_Polzovateli { get; set; }
        public virtual DbSet<Demo_Roli> Demo_Roli { get; set; }
    }
}
